input.onSound(DetectedSound.Loud, function () {
    basic.pause(200)
    pins.servoWritePin(AnalogPin.P1, 0)
    pins.servoWritePin(AnalogPin.P2, 0)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 90)
})
input.onButtonPressed(Button.A, function () {
    Affichage.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P1, 180)
    pins.servoWritePin(AnalogPin.P2, 0)
    basic.pause(2000)
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 90)
    Affichage.clear()
    Affichage.show()
})
input.onButtonPressed(Button.AB, function () {
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 90)
})
input.onButtonPressed(Button.B, function () {
    Affichage.setPixelColor(0, neopixel.colors(NeoPixelColors.White))
    Affichage.setPixelColor(4, neopixel.colors(NeoPixelColors.White))
    Affichage.show()
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P1, 0)
    pins.servoWritePin(AnalogPin.P2, 180)
    basic.pause(2000)
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 90)
    Affichage.clear()
    Affichage.show()
})
input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    Affichage.showRainbow(1, 360)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P1, 180)
    pins.servoWritePin(AnalogPin.P2, 180)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 90)
    Affichage.clear()
    Affichage.show()
})
let Affichage: neopixel.Strip = null
input.setSoundThreshold(SoundThreshold.Loud, 230)
Affichage = neopixel.create(DigitalPin.P0, 5, NeoPixelMode.RGB)
pins.servoWritePin(AnalogPin.P1, 90)
pins.servoWritePin(AnalogPin.P2, 90)
